### ISSUE TITLE
MasterPass Resist to keylogers

### ISSUE THREAD

**Issue by sctfic** [lesspass/frontend#4]
serai t il possible de ne pas saisir le Master PassWord au clavier mais plutôt a la sourie (choix possible) ?

ou même cliquer sur les icones pour reconstituer le finger a la sourie, au lieux du masteur PassWord.

ainsi même sur un poste "Pourri" lesspass reste Sûr

**Comment by guillaumevincent** [comment]
This issue was moved to lesspass/lesspass#25
